

numero1 = 4
#numero2 = 6
numero2 = "6"

try: 
    print(numero1 + numero2)

except:
    print("Se ha producido un error")

# El codigo se ejecutara aunque haya un error